export enum PAGINATION_DEFAULTS {
  PAGE = 1,
  LIMIT = 10,
}

export const PAGE_SIZE_OPTIONS = ["10", "20", "50", "100"];

export const DATE_FORMAT_ISO = "YYYY-MM-DD";


export const SERVICE_CATEGORIES = {
  ASSISTANCE: "ASSISTANCE",
  COMPANIONSHIP: "COMPANIONSHIP",
  PERSONAL_ASSISTANT: "PERSONAL_ASSISTANT",
  ON_SITE_PROFESSIONAL_ASSIST: "ON_SITE_PROFESSIONAL_ASSIST",
  VIRTUAL_ASSISTANT: "VIRTUAL_ASSISTANT",
  TOUR_GUIDE: "TOUR_GUIDE",
  TRANSLATOR: "TRANSLATOR",
  COMPANIONSHIP_LEVEL_1: "COMPANIONSHIP_LEVEL_1",
  COMPANIONSHIP_LEVEL_2: "COMPANIONSHIP_LEVEL_2",
  COMPANIONSHIP_LEVEL_3: "COMPANIONSHIP_LEVEL_3",
} as const;