export const TIME_CONSTANTS = {
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_YEAR: 365,
} as const;

export const TIME_IN_MS = {
  SECOND: TIME_CONSTANTS.MILLISECONDS_PER_SECOND,
  MINUTE:
    TIME_CONSTANTS.MILLISECONDS_PER_SECOND * TIME_CONSTANTS.SECONDS_PER_MINUTE,
  HOUR:
    TIME_CONSTANTS.MILLISECONDS_PER_SECOND *
    TIME_CONSTANTS.SECONDS_PER_MINUTE *
    TIME_CONSTANTS.MINUTES_PER_HOUR,
  DAY:
    TIME_CONSTANTS.MILLISECONDS_PER_SECOND *
    TIME_CONSTANTS.SECONDS_PER_MINUTE *
    TIME_CONSTANTS.MINUTES_PER_HOUR *
    TIME_CONSTANTS.HOURS_PER_DAY,
  YEAR:
    TIME_CONSTANTS.MILLISECONDS_PER_SECOND *
    TIME_CONSTANTS.SECONDS_PER_MINUTE *
    TIME_CONSTANTS.MINUTES_PER_HOUR *
    TIME_CONSTANTS.HOURS_PER_DAY *
    TIME_CONSTANTS.DAYS_PER_YEAR,
} as const;

export const TOKEN_EXPIRY = {
  CSRF_TOKEN_HOURS: 24,
  PASSWORD_RESET_MINUTES: 15,
  EMAIL_VERIFICATION_HOURS: 24,
} as const;

export const RATE_LIMIT_WINDOWS = {
  AUTH_MINUTES: 15,
  REFRESH_TOKEN_HOURS: 1,
  EMAIL_ACTION_HOURS: 1,
} as const;
