export const VALIDATION_LIMITS = {
  PASSWORD_MIN_LENGTH: 8,
  FULL_NAME_MAX_LENGTH: 100,
  PHONE_MAX_LENGTH: 20,
  PAGINATION_MAX_LIMIT: 100,
  PAGINATION_DEFAULT_PAGE: 1,
  PAGINATION_DEFAULT_LIMIT: 10,
} as const;
