export enum ErrorCode {
  EMAIL_EXISTS = "EMAIL_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_TOKEN = "INVALID_TOKEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  USER_BANNED = "USER_BANNED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  CSRF_TOKEN_MISSING = "CSRF_TOKEN_MISSING",
  CSRF_TOKEN_INVALID = "CSRF_TOKEN_INVALID",
  INVALID_ORIGIN = "INVALID_ORIGIN",
  INVALID_REFERER = "INVALID_REFERER",
  MISSING_ORIGIN = "MISSING_ORIGIN",
  WALLET_INSUFFICIENT_BALANCE = "WALLET_INSUFFICIENT_BALANCE",
  WALLET_INVALID_AMOUNT = "WALLET_INVALID_AMOUNT",
  WALLET_TRANSACTION_NOT_FOUND = "WALLET_TRANSACTION_NOT_FOUND",
  WALLET_TRANSACTION_FAILED = "WALLET_TRANSACTION_FAILED",
  WALLET_PAYMENT_VERIFICATION_FAILED = "WALLET_PAYMENT_VERIFICATION_FAILED",
  WALLET_DEPOSIT_AMOUNT_TOO_LOW = "WALLET_DEPOSIT_AMOUNT_TOO_LOW",
  WALLET_DEPOSIT_AMOUNT_TOO_HIGH = "WALLET_DEPOSIT_AMOUNT_TOO_HIGH",
}

export interface ValidationErrorDetail {
  field: string;
  message: string;
}

export interface ErrorResponse {
  success: false;
  error: {
    code: ErrorCode;
    message: string;
    details?: ValidationErrorDetail[];
  };
}

export interface SuccessResponse<T = unknown> {
  success: true;
  data: T;
}

export type ApiResponse<T = unknown> = SuccessResponse<T> | ErrorResponse;
