export enum ErrorCode {
  EMAIL_EXISTS = "EMAIL_EXISTS",
  EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_TOKEN = "INVALID_TOKEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  USER_BANNED = "USER_BANNED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  CSRF_TOKEN_MISSING = "CSRF_TOKEN_MISSING",
  CSRF_TOKEN_INVALID = "CSRF_TOKEN_INVALID",
  INVALID_ORIGIN = "INVALID_ORIGIN",
  INVALID_REFERER = "INVALID_REFERER",
  MISSING_ORIGIN = "MISSING_ORIGIN",
  WALLET_INSUFFICIENT_BALANCE = "WALLET_INSUFFICIENT_BALANCE",
  WALLET_INVALID_AMOUNT = "WALLET_INVALID_AMOUNT",
  WALLET_TRANSACTION_NOT_FOUND = "WALLET_TRANSACTION_NOT_FOUND",
  WALLET_TRANSACTION_FAILED = "WALLET_TRANSACTION_FAILED",
  WALLET_PAYMENT_VERIFICATION_FAILED = "WALLET_PAYMENT_VERIFICATION_FAILED",
  WALLET_DEPOSIT_AMOUNT_TOO_LOW = "WALLET_DEPOSIT_AMOUNT_TOO_LOW",
  WALLET_DEPOSIT_AMOUNT_TOO_HIGH = "WALLET_DEPOSIT_AMOUNT_TOO_HIGH",
  BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND",
  BOOKING_INVALID_STATUS = "BOOKING_INVALID_STATUS",
  BOOKING_INVALID_SCHEDULE = "BOOKING_INVALID_SCHEDULE",
  BOOKING_INVALID_PRICING = "BOOKING_INVALID_PRICING",
  BOOKING_ALREADY_EXISTS = "BOOKING_ALREADY_EXISTS",
  BOOKING_UNAUTHORIZED_ACCESS = "BOOKING_UNAUTHORIZED_ACCESS",
  BOOKING_CANNOT_CANCEL = "BOOKING_CANNOT_CANCEL",
  BOOKING_CANNOT_UPDATE = "BOOKING_CANNOT_UPDATE",
  BOOKING_INVALID_STATUS_TRANSITION = "BOOKING_INVALID_STATUS_TRANSITION",
  BOOKING_SELF_BOOKING_NOT_ALLOWED = "BOOKING_SELF_BOOKING_NOT_ALLOWED",
  ESCROW_RELEASE_FAILED = "ESCROW_RELEASE_FAILED",
  BOOKING_ALREADY_DISPUTED = "BOOKING_ALREADY_DISPUTED",
  BOOKING_NOT_DISPUTED = "BOOKING_NOT_DISPUTED",
  DISPUTE_CANNOT_RESOLVE = "DISPUTE_CANNOT_RESOLVE",
  REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",
  REVIEW_ALREADY_EXISTS = "REVIEW_ALREADY_EXISTS",
  REVIEW_UNAUTHORIZED_ACCESS = "REVIEW_UNAUTHORIZED_ACCESS",
  REVIEW_INVALID_RATING = "REVIEW_INVALID_RATING",
  REVIEW_CANNOT_UPDATE = "REVIEW_CANNOT_UPDATE",
  ESCROW_NOT_FOUND = "ESCROW_NOT_FOUND",
  ESCROW_UNAUTHORIZED_ACCESS = "ESCROW_UNAUTHORIZED_ACCESS",
  POST_NOT_FOUND = "POST_NOT_FOUND",
  POST_UNAUTHORIZED_ACCESS = "POST_UNAUTHORIZED_ACCESS",
  POST_MEDIA_LIMIT_EXCEEDED = "POST_MEDIA_LIMIT_EXCEEDED",
  COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
  COMMENT_NESTED_REPLY_NOT_ALLOWED = "COMMENT_NESTED_REPLY_NOT_ALLOWED",
  COMMENT_PARENT_POST_MISMATCH = "COMMENT_PARENT_POST_MISMATCH",
  COMMENT_UNAUTHORIZED_ACCESS = "COMMENT_UNAUTHORIZED_ACCESS",
}

export interface ValidationErrorDetail {
  field: string;
  message: string;
}

export interface ErrorResponse {
  success: false;
  error: {
    code: ErrorCode;
    message: string;
    details?: ValidationErrorDetail[];
  };
}

export interface SuccessResponse<T = unknown> {
  success: true;
  data: T;
}

export type ApiResponse<T = unknown> = SuccessResponse<T> | ErrorResponse;
