export const modelsName = {
  USER: "users",
  CONVERSATION: "conversations",
  CONVERSATION_GROUP: "conversations_group",
  SERVICE: "service",
  WORKER_SERVICE: "worker_service",
  MESSAGE: "messages",
  MESSAGE_GROUP: "messages_group",
  WALLET_TRANSACTION: "wallet_transactions",
  WALLET: "wallets",
  ESCROW: "escrows",
  BOOKING: "bookings",
  REVIEW: "reviews",
  NOTIFICATION: "notifications",
  NOTIFICATION_PREFERENCE: "notification_preferences",
  PUSH_SUBSCRIPTION: "push_subscriptions",
  NOTIFICATION_DELIVERY_LOG: "notification_delivery_logs",
  LOCATION: "locations",
};

