export enum ApiEndpoint {
  AUTH_REGISTER = "/auth/register",
  AUTH_LOGIN = "/auth/login",
  AUTH_REFRESH_TOKEN = "/auth/refresh-token",
  AUTH_ME = "/auth/me",
  AUTH_LOGOUT = "/auth/logout",
  AUTH_SWITCH_ROLE = "/auth/switch-role",
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  AUTH_PROFILE = "/auth/me",
  AUTH_UPDATE_PROFILE = "/auth/update-profile",
  AUTH_FORGOT_PASSWORD = "/auth/forgot-password",
  AUTH_RESET_PASSWORD = "/auth/reset-password",
  AUTH_VERIFY_EMAIL = "/auth/verify-email",
  AUTH_RESEND_VERIFICATION = "/auth/resend-verification",
  USERS = "/users",
  USERS_STATUS = "/users/:id/status",
  SERVICES = "/services",
  SERVICES_BY_ID = "/services/:id",
  SERVICES_BY_CODE = "/services/code/:code",
  WORKERS_BY_ID = "/workers/:id",
  WORKERS_BY_ID_SCHEDULE = "/workers/:id/schedule",
  WORKERS_GROUPED_BY_SERVICE = "/workers/grouped-by-service",
  WORKERS_LOCATION_SUGGESTIONS = "/workers/location-suggestions",
  WORKER_SERVICES = "/worker/services",
  WORKER_SERVICES_BY_ID = "/worker/services/:serviceId",
  CHAT_MESSAGES = "/chat/messages",
  CHAT_MESSAGES_BY_ID = "/chat/messages/:message_id",
  CHAT_MESSAGES_READ = "/chat/messages/read",
  CHAT_MESSAGES_UNREAD = "/chat/messages/unread",
  CHAT_CONVERSATIONS = "/chat/conversations",
  CHAT_CONVERSATIONS_BY_ID = "/chat/conversations/:conversation_id",
  CHAT_GROUP_MESSAGES = "/chat/group/messages",
  CHAT_GROUP_MESSAGES_READ = "/chat/group/messages/read",
  CHAT_GROUP_MESSAGES_UNREAD = "/chat/group/messages/unread",
  CHAT_GROUP_CONVERSATIONS = "/chat/group/conversations",
  CHAT_GROUP_CONVERSATIONS_BY_ID = "/chat/group/conversations/:conversation_group_id",
  CHAT_GROUP_COMPLAINT = "/chat/group/complaint",
  WALLET_DEPOSIT = "/wallet/deposit",
  WALLET_DEPOSIT_CALLBACK = "/wallet/deposit/callback",
  WALLET_BALANCE = "/wallet/balance",
  WALLET_TRANSACTIONS = "/wallet/transactions",
  ADMIN_WALLET_TRANSACTIONS = "/admin/wallet/transactions",
  ADMIN_WALLET_STATS = "/admin/wallet/stats",
  ADMIN_WALLET_TOP_USERS = "/admin/wallet/top-users",
  ADMIN_WALLET_CHART = "/admin/wallet/chart",
  PRICING_PACKAGES = "/pricing/packages",
  PRICING_ME = "/pricing/me",
  PRICING_UPGRADE = "/pricing/upgrade",
  ADMIN_PRICING_PACKAGES = "/pricing/packages/admin",
  ADMIN_PRICING_PACKAGE_BY_ID = "/pricing/packages/admin/:id",
  BOOKINGS = "/bookings",
  BOOKINGS_MY = "/bookings/my",
  BOOKINGS_ALL = "/bookings/all",
  BOOKINGS_BY_ID = "/bookings/:id",
  BOOKINGS_BY_ID_STATUS = "/bookings/:id/status",
  BOOKINGS_BY_ID_CANCEL = "/bookings/:id/cancel",
  BOOKINGS_BY_ID_DISPUTE = "/bookings/:id/dispute",
  BOOKINGS_BY_ID_DISPUTE_RESOLVE = "/bookings/:id/dispute/resolve",
  REVIEWS = "/reviews",
  REVIEWS_MY = "/reviews/my",
  REVIEWS_BY_ID = "/reviews/:id",
  ESCROWS_MY = "/escrows/my",
  ESCROWS_ALL = "/escrows/all",
  ESCROWS_BY_ID = "/escrows/:id",
  NOTIFICATIONS = "/notifications",
  NOTIFICATIONS_UNREAD_COUNT = "/notifications/unread-count",
  NOTIFICATIONS_BY_ID_READ = "/notifications/:id/read",
  NOTIFICATIONS_READ_ALL = "/notifications/read-all",
  NOTIFICATIONS_PREFERENCES = "/notifications/preferences",
  NOTIFICATIONS_PUSH_PUBLIC_KEY = "/notifications/push-public-key",
  NOTIFICATIONS_PUSH_SUBSCRIPTIONS = "/notifications/push-subscriptions",
  NOTIFICATIONS_PUSH_SUBSCRIPTIONS_BY_ID = "/notifications/push-subscriptions/:id",
  POSTS = "/posts",
  POSTS_BY_ID = "/posts/:id",
  POSTS_COMMENTS = "/posts/:postId/comments",
  COMMENTS_BY_ID = "/comments/:id",
  HASHTAGS_TRENDING = "/hashtags/trending",
  USERS_ME_POST_STATS = "/users/me/post-stats",
}

export const buildEndpoint = (
  endpoint: ApiEndpoint,
  params?: Record<string, string>
): string => {
  let path: string = endpoint;
  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      path = path.replace(`:${key}`, value);
    });
  }
  return path;
};
