export const BOOKING_CONSTANTS = {
  MIN_ADVANCE_HOURS: 2,
  MAX_ADVANCE_DAYS: 30,
  MIN_DURATION_HOURS: 1,
  MAX_DURATION_HOURS: 24,
  PLATFORM_FEE_PERCENT: 2,
} as const;

export const BOOKING_TIME_SLOTS = {
  START_HOUR: 8,
  END_HOUR: 22,
  SLOT_DURATION_MINUTES: 30,
} as const;
