export enum AuthErrorCode {
  INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
  ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED",
  TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID",
  EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  WEAK_PASSWORD = "AUTH_WEAK_PASSWORD",
  INVALID_EMAIL_FORMAT = "AUTH_INVALID_EMAIL_FORMAT",
}

export enum ChatErrorCode {
  SEND_MESSAGE_FAILED = "CHAT_SEND_MESSAGE_FAILED",
  DELETE_MESSAGE_FAILED = "CHAT_DELETE_MESSAGE_FAILED",
  CONVERSATION_NOT_FOUND = "CHAT_CONVERSATION_NOT_FOUND",
  MESSAGE_NOT_FOUND = "CHAT_MESSAGE_NOT_FOUND",
  UNAUTHORIZED_ACCESS = "CHAT_UNAUTHORIZED_ACCESS",
  RATE_LIMIT_EXCEEDED = "CHAT_RATE_LIMIT_EXCEEDED",
}

export enum WalletErrorCode {
  DEPOSIT_FAILED = "WALLET_DEPOSIT_FAILED",
  WITHDRAW_FAILED = "WALLET_WITHDRAW_FAILED",
  INSUFFICIENT_BALANCE = "WALLET_INSUFFICIENT_BALANCE",
  INVALID_AMOUNT = "WALLET_INVALID_AMOUNT",
  PAYMENT_GATEWAY_ERROR = "WALLET_PAYMENT_GATEWAY_ERROR",
  TRANSACTION_NOT_FOUND = "WALLET_TRANSACTION_NOT_FOUND",
  VERIFICATION_FAILED = "WALLET_VERIFICATION_FAILED",
}

export enum NetworkErrorCode {
  TIMEOUT = "NETWORK_TIMEOUT",
  CONNECTION_FAILED = "NETWORK_CONNECTION_FAILED",
  UNKNOWN = "NETWORK_UNKNOWN",
}

export enum ValidationErrorCode {
  REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD",
  INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  OUT_OF_RANGE = "VALIDATION_OUT_OF_RANGE",
  INVALID_TYPE = "VALIDATION_INVALID_TYPE",
}

export enum ServerErrorCode {
  INTERNAL_ERROR = "SERVER_INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVER_SERVICE_UNAVAILABLE",
  BAD_GATEWAY = "SERVER_BAD_GATEWAY",
}
